DROP DATABASE IF EXISTS TIENDAMUSICAL;
CREATE DATABASE TIENDAMUSICAL;
USE TIENDAMUSICAL;

-- Tabla SOCIOS
CREATE TABLE SOCIOS (
  ID_SOCIO INT AUTO_INCREMENT PRIMARY KEY,
  NOMBRE1 VARCHAR(50) NOT NULL,
  NOMBRE2 VARCHAR(50),
  APELLIDO1 VARCHAR(50) NOT NULL,
  APELLIDO2 VARCHAR(50),
  DNI INT NOT NULL UNIQUE,
  EMAIL VARCHAR(100),
  TELEFONO VARCHAR(15) NOT NULL,
  CALLE VARCHAR(100),
  NUMERO VARCHAR(5),
  COD_POSTAL VARCHAR(6)
);

-- Tabla TIPO
CREATE TABLE TIPO (
  ID_TIPO VARCHAR(3) PRIMARY KEY,         -- Ej: VIN, DVD, CAS
  DESCRIPCION VARCHAR(20) NOT NULL        -- Ej: Vinilo, DVD, Cassette
);

-- Tabla ESTADO
CREATE TABLE ESTADO (
  ID_ESTADO VARCHAR(3) PRIMARY KEY,        -- Ej: BUE, USA, MAL, REG
  DESCRIPCION VARCHAR(20) NOT NULL         -- Ej: Bueno, Usado, Mal, Regular
);

-- Tabla ALBUM
CREATE TABLE ALBUM (
  ID_ALBUM INT AUTO_INCREMENT PRIMARY KEY,
  TITULO VARCHAR(100) NOT NULL UNIQUE,
  ARTISTA VARCHAR(150) NOT NULL,
  ANIO INT,                               
  PRODUCTORA VARCHAR(100),
  GENERO VARCHAR(50),
  DURACION INT,                           -- En minutos
  NRO_CANCIONES INT
);

-- Tabla DISTRIBUIDORA
CREATE TABLE DISTRIBUIDORA (
  ID_DISTRIBUIDORA INT AUTO_INCREMENT PRIMARY KEY,
  NOMBRE_DSTR VARCHAR(50),
  CALLE VARCHAR(100),
  NUMERO VARCHAR(5),
  PAGINA VARCHAR(50),
  EMAIL VARCHAR(100)
);

-- Tabla COPIAS
CREATE TABLE COPIAS (
  ID_COPIA INT PRIMARY KEY AUTO_INCREMENT,
  TIPO VARCHAR(3) NOT NULL,
  ALBUM INT NOT NULL,
  DISTRIBUIDORA INT NOT NULL,
  ESTADO VARCHAR(3) NOT NULL,
  OBSERVACIONES VARCHAR(255),
  FOREIGN KEY (TIPO) REFERENCES TIPO(ID_TIPO)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  FOREIGN KEY (ALBUM) REFERENCES ALBUM(ID_ALBUM)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  FOREIGN KEY (DISTRIBUIDORA) REFERENCES DISTRIBUIDORA(ID_DISTRIBUIDORA)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  FOREIGN KEY (ESTADO) REFERENCES ESTADO(ID_ESTADO)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

-- Tabla PRESTAMO
CREATE TABLE PRESTAMO (
  ID_PRESTAMO INT AUTO_INCREMENT PRIMARY KEY,
  FECHA_PRESTAMO DATE NOT NULL,
  FECHA_DEVOLUCION DATE,
  FECHA_TOPE DATE,
  PRECIO DECIMAL(6,2) NOT NULL,
  OBSERVACIONES VARCHAR(255),
  ID_SOCIO INT NOT NULL,
  FOREIGN KEY (ID_SOCIO) REFERENCES SOCIOS(ID_SOCIO)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
  ID_COPIA INT NOT NULL,
  FOREIGN KEY (ID_COPIA) REFERENCES COPIAS(ID_COPIA)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
);